### ISSUE TITLE
Clarify batch size units

### ISSUE THREAD

**Issue by tomMcGrath** [jbloomAus/SAELens#131]
Currently 'batch size' refers to two distinct units in different places: tokens and sequences. The referenced comment suggests a naming scheme that would distinguish this.

              @tomMcGrath  @tomMcGrath We previously has "train_batch_size" which is a token batch size for the SAE and a "store batch size" which was a prompts batch size for generating activations. The latter was then reused during evaluations, but we've now seperated them out. I think the following names might be best:
- train_batch_size_tokens
- store_batch_size_prompts
- eval_batch_size_prompts 
I generally like longer names if they are sufficiently clear but will admit these names are long and this could be annoying.

_Originally posted by @jbloomAus in https://github.com/jbloomAus/SAELens/issues/128#issuecomment-2100974038_

**Comment by chanind** [comment]
fixed in #133
