### ISSUE TITLE
[Proposal] add the loading SAE from Huggingface utils to TransformerLens

### ISSUE THREAD

**Issue by ArthurConmy** [jbloomAus/SAELens#135]
### Proposal, Motivation, Pitch

The great utils here: https://github.com/jbloomAus/SAELens/blob/007141e67a447f8dfe8d6797a6fba0fc4fce61bd/sae_lens/toolkit/pretrained_saes.py#L22 would really help https://github.com/TransformerLensOrg/TransformerLens/pull/584 work for arbitrary SAEs on HuggingFace (as suggested by @danbraunai ).

How would @jbloomAus you feel about me adding (a version of) that util to TransformerLens and then making the SAELens code use those instead?

### Alternatives

Copy and pasted code in TransformerLens

### Additional context

N/A

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/jbloomAus/SAELens/issues) in the repo (**required**)

**Comment by jbloomAus** [comment]
My high level take is that transformer lens probably should have a util like this but I wouldn't want to depend on it in SAELens. SAE Lens can't depend on another library for something this fundamental.
