### ISSUE TITLE
[Proposal] Current session loading process can be very confusing and should be simpler

### ISSUE THREAD

**Issue by FabienRoger** [jbloomAus/SAELens#145]
*Not a real and complete proposal, mostly a note from a chat with @jbloomAus.*

### Proposal 

There should be a simple and documented way to load a (model, sae, dataset).

Ideally, there should be a way to load (model, sae) or model then sae, and a way to load a dataset that is more straightforward (or just documented) than ActivationsStore (which I wouldn't have guessed was the main dataloader).

### Motivation

The version from the docs is broken, and somewhat confusion (e.g. it's hard to know how to use another dataset with that API).

### Checklist

- [ x ] I have checked that there is no similar [issue](https://github.com/jbloomAus/SAELens/issues) in the repo

**Comment by jbloomAus** [comment]
This is out of date (but I think mostly resolved by various changes we've made since then :) )
