### ISSUE TITLE
[Proposal] Make it easier to diagnose accidental dataset/tokenizer mismatch

### ISSUE THREAD

**Issue by tomMcGrath** [jbloomAus/SAELens#146]
### Proposal 

Make it easier to avoid accidentally running SAE training with a pretokenised dataset whose tokeniser doesn't match the model. I've done this a few times and the only symptom is anomalously high CE scores. This makes the outputs of the sweeps useless: the model is fitting noise.

### Pitch

Potential fixes for this:
- Simple: occasionally log detokenized text from get_batch_tokens in W&B
- Complex but robust: some preflight checking for compatibility of model tokeniser and dataset (assuming suitable metadata exists)

### Additional context

Here's an example run that suffered from this issue: https://wandb.ai/tmcgrath/gpt-2-sweep-13may24/workspace?nw=nwusertmcgrath

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/jbloomAus/SAELens/issues) in the repo (**required**)

**Comment by chanind** [comment]
The pretokenize runner includes metadata about the tokenizer and settings used, so if the dataset is generate via that runner it should be possible to do an automated check.

One possible issue though is that often similar models use the same tokenizer with different names, e.g. `gpt2` vs `gpt2-large` likely use the same underlying tokenizer even though the name is different. Maybe we can add some sort of `tokenizer_checksum` field to the metadata, where we take a string of text and its tokenized output, and then JSON-encode / base64 encode the result into some sort of a checksum that we can use as a sanity check? Or maybe we can just download both the tokenizer specified by the dataset metadata and the tokenizer from the training model and verify they have the same settings?
