### ISSUE TITLE
[Bug Report] docs: Slack link is broken

### ISSUE THREAD

**Issue by domdomegg** [jbloomAus/SAELens#180]
**Describe the bug**
In the repo README, there's a line "Feel free to join the [Open Source Mechanistic Interpretability Slack](https://join.slack.com/t/opensourcemechanistic/shared_invite/zt-1qosyh8g3-9bF3gamhLNJiqCL_QqLFrA) for support!". But this link appears to be broken:

<img width="868" alt="image" src="https://github.com/jbloomAus/SAELens/assets/4953590/37a9c14f-27c0-41ce-a752-dfde3db13153">

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/jbloomAus/SAELens/issues) in the repo (**required**)

**Comment by jbloomAus** [comment]
Ahh sorry. Should be fixed. Try again?

**Comment by domdomegg** [comment]
Yup that works :)
