### ISSUE TITLE
[Proposal] Allow loading TransformerLens models saved locally

### ISSUE THREAD

**Issue by chanind** [jbloomAus/SAELens#185]
### Proposal 

Allow loading TransformerLens models saved locally

### Motivation

Currently, we require that any model an SAE is trained on must be a public-facing, official model on TransformerLens. This is very limiting, however, since it means it's not possible to experiment on custom-trained models locally as seen in https://github.com/jbloomAus/SAELens/pull/177. We should allow loading a model saved locally.

### Pitch

We should add a `local_model_path` option to the config to specify where the model is located locally, and load from there.

### Alternatives

We could allow passing a local file path to `model_name` and just load the model from the path if it exists, similar to how Huggingface works.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/jbloomAus/SAELens/issues) in the repo (**required**)

**Comment by jbloomAus** [comment]
This was completed. Closing.
