### ISSUE TITLE
[Proposal] Add note that Windows unsupported

### ISSUE THREAD

**Issue by MClarke1991** [jbloomAus/SAELens#190]
### Proposal 

Make a note on README that package does not support Windows. 

### Motivation

Package requires automated-interpretability = "^0.0.3" which in turn depends on uv-loop which does not support Windows. 

### Pitch

As above

### Alternatives

NA

### Additional context

NA

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/jbloomAus/SAELens/issues) in the repo (**required**)

**Comment by jbloomAus** [comment]
Automated interpretability isn't core to the package so we should really make that dependency optional and flag it if users try to use that sub package.

**Comment by mivanit** [comment]
automated-interpretability requires boostedblob, which in turn required uvloop, but this dependency should have been optional. as of [this PR, merged in boostedblob 0.15.4](https://github.com/hauntsaninja/boostedblob/pull/25), uvloop is only a dep if the platform is not windows. I tested installing SAELens from pip on a windows machine and it seems to work .

**Comment by MClarke1991** [comment]
Can confirm `pip install sae_lens` works for me on Windows 10 now as well, thanks!
