### ISSUE TITLE
How to reproduce jbloom/Gemma-2b-Residual-Stream-SAEs

### ISSUE THREAD

**Issue by zdaiot** [jbloomAus/SAELens#191]
Thank you for your excellent work. I'd like to know how to reproduce jbloom/Gemma-2b-Residual-Stream-SAEs

Can you open source the configuration file for training it?

**Comment by ianand** [comment]
Is https://huggingface.co/jbloom/Gemma-2b-Residual-Stream-SAEs/blob/main/gemma_2b_blocks.12.hook_resid_post_16384/cfg.json what you're looking for?

**Comment by jbloomAus** [comment]
@zdaiot  Usually we like to use the training data to train the SAE but we often don't know what that is. Pre-tokenized datasets are better and we have a utility for generating those now. It gets more complicated if you want to work with instruction fine tuned datasets and I have no special insights here.

**Comment by jbloomAus** [comment]
@zdaiot let me know if I can close this :)

**Comment by zdaiot** [comment]
@jbloomAus May I ask if the same dataset is needed when training the SAE and analyzing the SAE?

**Comment by jbloomAus** [comment]
@zdaiot this is an open research question.
