### ISSUE TITLE
[Bug Report]  SAE.from_pretrained errors out in Hooked_SAE_Transformer_Demo.ipynb

### ISSUE THREAD

**Issue by babcockt18** [jbloomAus/SAELens#193]
**Describe the bug**
SAE.from_pretrained in `tutorials/Hooked_SAE_Transformer_Demo.ipynb` returns 
``TypeError: SAEConfig.__init__() missing 1 required positional argument: 'dataset_trust_remote_code'``

**Code example**
I ran the cells in the proper order and returned the below errors
![image](https://github.com/jbloomAus/SAELens/assets/39506616/5e703e98-5ac2-4d3c-958c-d21908515d88)

**System Info**
 * Google Colab Demo notebook

**Additional context**
My current hunch is that the addition of [dataset_trust_remote_code](https://github.com/jbloomAus/SAELens/commit/33a612d7f694390a5a4596f7e15e0c51657634ba#:~:text=%3Dcfg.-,dataset_trust_remote_code,-%2C) wasn't propogated to the [preconfigured dictionary](https://github.com/jbloomAus/SAELens/blob/623a1eb6cd35a9aa230514c13b22f8e418505def/sae_lens/toolkit/pretrained_sae_loaders.py#L68) which needs the parameter added to fix the issue.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/jbloomAus/SAELens/issues) in the repo (**required**)

**Comment by aayushk61466** [comment]
hey,
I am also facing the same issue. 
@babcockt18 is there a way around this?

**Comment by jbloomAus** [comment]
should be fixed
