### ISSUE TITLE
[Proposal] Save norm scaling factor

### ISSUE THREAD

**Issue by ckkissane** [jbloomAus/SAELens#222]
### Proposal 

After training, the scaling factor from ActivationsStore.estimate_norm_scaling_factor is lost. I propose storing it in wandb, or even just logging it as an MVP.

### Motivation

Lately i've trained multiple SAEs and want to quickly run evals on them. I can recompute the scaling factors myself, but this takes several minutes per each SAE.

### Checklist

- [x ] I have checked that there is no similar [issue](https://github.com/jbloomAus/SAELens/issues) in the repo (**required**)

**Comment by jbloomAus** [comment]
solved.
