### ISSUE TITLE
[Bug Report] read_sae_from_disk should default to the SAE dtype unless it's overridden

### ISSUE THREAD

**Issue by hijohnnylin** [jbloomAus/SAELens#230]
**Describe the bug**
`sae_lens_loader` in `pretrained_sae_loaders.py` currently does not pass in `dtype` into `read_sae_from_disk`, so it always initializes weights using `float32` first.

The dtype is correct at the very end, since `sae` is created/initialized with the correct dtype from cfg_dict. However, ideally we would be using the correct dtype the whole time.

The fix seems to be that `read_sae_from_disk` should 1) make dtype optional and 2) use the dtype specified by the cfg_dict by default, if dtype is not specified. This has the benefit that other methods calling `read_sae_from_disk` would have the correct behavior by default, unless they choose to override.

I'll make a PR for this soon.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/jbloomAus/SAELens/issues) in the repo (**required**)

**Comment by anthonyduong9** [comment]
@hijohnnylin why would someone not want to use `cfg_dict["dtype"]`? It's not clear to me and was wondering if we should also remove the `dtype` param.

Either way, I know how to fix this issue so can open a PR to do so.

**Comment by hijohnnylin** [comment]
> @hijohnnylin why would someone not want to use `cfg_dict["dtype"]`? It's not clear to me and was wondering if we should also remove the `dtype` param.
> 
> Either way, I know how to fix this issue so can open a PR to do so.

Hmm it's a good question. I haven't looked at this in awhile and @curt-tigges can probably answer this better, but from what I understand, the SAE Config itself has a dtype that it was trained with, but we don't always want to use that same dtype when loading the SAE. One reason is that we want to save memory when loading the SAE.

There are dtype overrides in function arguments in many places, but I'm not sure what the reason is - but I assume @jbloomAus had good reason for adding them. I would advise to check with him or Curt before removing them outright.

**Comment by curt-tigges** [comment]
That is correct; there are situations where we want to specify the dtype differently during loading as opposed to training, mostly for memory-saving purposes. I am not sure how much this is used in practice, but it seems good to keep it for now.
