### ISSUE TITLE
[Proposal] Add use_error_term as an optional param for HookedSAETransformer.add_sae

### ISSUE THREAD

**Issue by neelnanda-io** [jbloomAus/SAELens#231]
### Proposal 

use_error_term is an SAE param for whether the output should be the reconstruction or the input. This is not part of the cfg, so not very visible to users, and it doesn't really matter unless the SAE is attached to the model. Having use_error_term as an optional parameter on add_sae is a natural way to make this option clear to the user, at the time when configuring it matters.

I propose that it defaults to None (change nothing) since sae may already have it set, but the option for users to force it to False or True.

It may also be reasonable to add it to run_with_saes and run_with_cache_with_saes, ideally which stores the initial config and reverts to that after the forward pass.

**Comment by jbloomAus** [comment]
@curt-tigges flagging this.
