### ISSUE TITLE
[Bug Report] sae-lens and umap-learn compatibility issue

### ISSUE THREAD

**Issue by wlg1** [jbloomAus/SAELens#246]
**Describe the bug**
In Colab, when running `%pip install sae-lens` before `%pip install umap-learn` , then running `import umap` gives an error `AttributeError: module 'numpy.linalg._umath_linalg' has no attribute '_ilp64`'. 

Also running `%pip install umap-learn` before `%pip install sae-lens`, then running`import umap` gives the same error. Of note is that running `%pip install umap-learn` , then running `import umap`, then `%pip install sae-lens `allows the usage of both umap and sae-lens functions without error (but must restart runtime after installing sae-lens to use pyarrow).

**Code example**

This shows the error message traceback in detail:

https://colab.research.google.com/drive/15wHJ5URCi4pSqZ9bkVxevk3dJ7eyA4dY?usp=sharing

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/jbloomAus/SAELens/issues) in the repo (**required**)

**Comment by chanind** [comment]
I think part of this is related to SAELens depending on `automated-interpretability`, which depends on a very recent version of numpy, more recent than what Colab comes pre-installed with. I'm not sure why it causes that numpy error (it seems like somehow Colab ends up with 2 different numpy versions), but afaict there's no reason why `automated-interpretability` needs such a recent version of numpy anyway. I opened a PR to automated-interpretability which should relax these requirements, and hopefully thus allow Colab to stick with its pre-installed numpy version when installing SAELens: https://github.com/hijohnnylin/automated-interpretability/pull/1.

In the meantime, I find running `%pip install numpy==1.25.2` in colab after installing SAELens allows things to keep working, but it's a pain to first force colab to install numpy 1.26.x, then immediately downgrade it again back to the version colab comes with.

**Comment by wlg1** [comment]
Thanks, using that numpy version in the meantime works!

**Comment by hijohnnylin** [comment]
Thanks @chanind. I've merged your PR and published a new version on PyPi. Let me know if this works as expected. From what I understand PyPi can take some time for releases to propagate.

**Comment by chanind** [comment]
Thanks @hijohnnylin!
