### ISSUE TITLE
[Proposal] Either explicitly check notebook formatting in CI, or exclude notebooks from make format

### ISSUE THREAD

**Issue by chanind** [jbloomAus/SAELens#287]
### Proposal 

Currently `make format` will format jupyter notebooks if the user has the black jupyter extension installed. We don't check this in CI though, so it can cause a huge amount of formatting changes for all notebooks when the users runs `make format`. We should either explicitly block `.ipynb` files from `make format`, or we should explicitly add the black jupyter extension as a dependency and check notebook formatting in CI.

My personal preference would be to add the black jupyter notebook plugin and explicitly check in CI to make our notebooks slightly more consistent, but also don't have a strong opinion.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/jbloomAus/SAELens/issues) in the repo (**required**)

**Comment by jbloomAus** [comment]
Seems good. I'd just format them.

**Comment by chanind** [comment]
Done by #318
