### ISSUE TITLE
[Proposal] Simplify SAE IDs for Gemma Scope Canonical SAEs

### ISSUE THREAD

**Issue by ArthurConmy** [jbloomAus/SAELens#289]
### Proposal 

Inotice that in

```
from sae_lens import SAE  # pip install sae-lens

sae, cfg_dict, sparsity = SAE.from_pretrained(
    release = "gemma-scope-2b-pt-res-canonical",
    sae_id = "layer_0/width_16k/canonical",
)
```

`canonical` in the `sae_id` is redundant and I suggest removing.

(I skipped the rest of the issue boilerplate)

**Comment by jbloomAus** [comment]
My personal vibe is this could introduce confusion this late in the game and that leaving it as is isn't terrible.

**Comment by ArthurConmy** [comment]
Seems completely reasonable 👍
