### ISSUE TITLE
[Bug Report]  When I‘m preparing SAE: ’non-default argument 'l1_coefficient' follows default argument

### ISSUE THREAD

**Issue by YokeYao** [jbloomAus/SAELens#313]
I'm running tutoriol_2_0.ipynb

When I reach the second part.
![image](https://github.com/user-attachments/assets/4e8e28c1-b796-437e-8269-90773d2a0884)

TypeError                                 Traceback (most recent call last)
Cell In[5], line 4
      1 from sae_lens.toolkit.pretrained_saes_directory import get_pretrained_saes_directory
      3 # TODO: Make this nicer.
----> 4 df = pd.DataFrame.from_records({k:v.__dict__ for k,v in get_pretrained_saes_directory().items()}).T
      5 df.drop(columns=["expected_var_explained", "expected_l0", "config_overrides", "conversion_func"], inplace=True)
      6 df

File ~/repeatcurse/sae_lens/toolkit/pretrained_saes_directory.py:27, in get_pretrained_saes_directory()
     25 # Access the file within the package using importlib.resources
     26 directory: dict[str, PretrainedSAELookup] = {}
---> 27 with resources.open_text(package, "pretrained_saes.yaml") as file:
     28     # Load the YAML file content
     29     data = yaml.safe_load(file)
     30     for release, value in data.items():

File ~/miniconda3/envs/py39_repeat/lib/python3.9/importlib/resources.py:121, in open_text(package, resource, encoding, errors)
    115 def open_text(package: Package,
    116               resource: Resource,
    117               encoding: str = 'utf-8',
    118               errors: str = 'strict') -> TextIO:
    119     """Return a file-like object opened for text reading of the resource."""
    120     return TextIOWrapper(
--> 121         open_binary(package, resource), encoding=encoding, errors=errors)

File ~/miniconda3/envs/py39_repeat/lib/python3.9/importlib/resources.py:88, in open_binary(package, resource)
     86 """Return a file-like object opened for binary reading of the resource."""
     87 resource = _normalize_path(resource)
---> 88 package = _get_package(package)
     89 reader = _get_resource_reader(package)
     90 if reader is not None:

File ~/miniconda3/envs/py39_repeat/lib/python3.9/importlib/resources.py:49, in _get_package(package)
     43 def _get_package(package) -> ModuleType:
     44     """Take a package name or module object and return the module.
     45 
     46     If a name, the module is imported.  If the resolved module
     47     object is not a package, raise an exception.
     48     """
---> 49     module = _resolve(package)
     50     if module.__spec__.submodule_search_locations is None:
     51         raise TypeError('{!r} is not a package'.format(package))

File ~/miniconda3/envs/py39_repeat/lib/python3.9/importlib/resources.py:40, in _resolve(name)
     38 if hasattr(name, '__spec__'):
     39     return name
---> 40 return import_module(name)

File ~/miniconda3/envs/py39_repeat/lib/python3.9/importlib/__init__.py:127, in import_module(name, package)
    125             break
    126         level += 1
--> 127 return _bootstrap._gcd_import(name[level:], package, level)

File <frozen importlib._bootstrap>:1030, in _gcd_import(name, package, level)

File <frozen importlib._bootstrap>:1007, in _find_and_load(name, import_)

File <frozen importlib._bootstrap>:986, in _find_and_load_unlocked(name, import_)

File <frozen importlib._bootstrap>:680, in _load_unlocked(spec)

File <frozen importlib._bootstrap_external>:850, in exec_module(self, module)

File <frozen importlib._bootstrap>:228, in _call_with_frames_removed(f, *args, **kwds)

File ~/repeatcurse/sae_lens/__init__.py:14
     12 from .pretokenize_runner import PretokenizeRunner, pretokenize_runner
     13 from .sae import SAE, SAEConfig
---> 14 from .sae_training_runner import SAETrainingRunner
     15 from .training.activations_store import ActivationsStore
     16 from .training.training_sae import TrainingSAE, TrainingSAEConfig

File ~/repeatcurse/sae_lens/sae_training_runner.py:17
     15 from sae_lens.training.activations_store import ActivationsStore
     16 from sae_lens.training.geometric_median import compute_geometric_median
---> 17 from sae_lens.training.sae_trainer import SAETrainer
     18 from sae_lens.training.training_sae import TrainingSAE, TrainingSAEConfig
     21 class InterruptedException(Exception):

File ~/repeatcurse/sae_lens/training/sae_trainer.py:16
     14 from sae_lens.training.activations_store import ActivationsStore
     15 from sae_lens.training.optim import L1Scheduler, get_lr_scheduler
---> 16 from sae_lens.training.training_sae import TrainingSAE, TrainStepOutput
     18 # used to map between parameters which are updated during finetuning and the config str.
     19 FINETUNING_PARAMETERS = {
     20     "scale": ["scaling_factor"],
     21     "decoder": ["scaling_factor", "W_dec", "b_dec"],
     22     "unrotated_decoder": ["scaling_factor", "b_dec"],
     23 }

File ~/repeatcurse/sae_lens/training/training_sae.py:40
     35     ghost_grad_loss: float
     36     auxiliary_reconstruction_loss: float = 0.0
     39 @dataclass
---> 40 class TrainingSAEConfig(SAEConfig):
     42     l1_coefficient: float
     43     lp_norm: float

File ~/miniconda3/envs/py39_repeat/lib/python3.9/dataclasses.py:1021, in dataclass(cls, init, repr, eq, order, unsafe_hash, frozen)
   1018     return wrap
   1020 # We're called as @dataclass without parens.
-> 1021 return wrap(cls)

File ~/miniconda3/envs/py39_repeat/lib/python3.9/dataclasses.py:1013, in dataclass.<locals>.wrap(cls)
   1012 def wrap(cls):
-> 1013     return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)

File ~/miniconda3/envs/py39_repeat/lib/python3.9/dataclasses.py:927, in _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
    923     # Include InitVars and regular fields (so, not ClassVars).
    924     flds = [f for f in fields.values()
    925             if f._field_type in (_FIELD, _FIELD_INITVAR)]
    926     _set_new_attribute(cls, '__init__',
--> 927                        _init_fn(flds,
    928                                 frozen,
    929                                 has_post_init,
    930                                 # The name to use for the "self"
    931                                 # param in __init__.  Use "self"
    932                                 # if possible.
    933                                 '__dataclass_self__' if 'self' in fields
    934                                         else 'self',
    935                                 globals,
    936                       ))
    938 # Get the fields as a list, and include only real fields.  This is
    939 # used in all of the following methods.
    940 field_list = [f for f in fields.values() if f._field_type is _FIELD]

File ~/miniconda3/envs/py39_repeat/lib/python3.9/dataclasses.py:504, in _init_fn(fields, frozen, has_post_init, self_name, globals)
    502             seen_default = True
    503         elif seen_default:
--> 504             raise TypeError(f'non-default argument {f.name!r} '
    505                             'follows default argument')
    507 locals = {f'_type_{f.name}': f.type for f in fields}
    508 locals.update({
    509     'MISSING': MISSING,
    510     '_HAS_DEFAULT_FACTORY': _HAS_DEFAULT_FACTORY,
    511 })

TypeError: non-default argument 'l1_coefficient' follows default argument

**System Info**
 * What OS are you using? (Linux) 
 * Python version 3.9
### Checklist

- [ ] I have checked that there is no similar [issue](https://github.com/jbloomAus/SAELens/issues) in the repo (**required**)

**Comment by anthonyduong9** [comment]
I'm unable to reproduce this on `main`, in a Python 3.11.9 environment, using CPU, or in a Colab notebook in a Python 3.10.12 environment. Have you tried in a Python 3.10 or higher environment?

https://github.com/jbloomAus/SAELens/blob/799ce005b207ac54a5efb34e8527f635b9e074ad/pyproject.toml#L21

**Comment by jbloomAus** [comment]
Thanks @anthonyduong9. @YokeYao , please let me know if that doesn't solve it. I will re-open the issue if so.

**Comment by YokeYao** [comment]
> Thanks @anthonyduong9. @YokeYao , please let me know if that doesn't solve it. I will re-open the issue if so.

Thanks for your help! I resolved the issue using Python 3.10. Apologies for not checking the notification in time.
