### ISSUE TITLE
[Proposal] Move to Ruff for linting / formatting

### ISSUE THREAD

**Issue by chanind** [jbloomAus/SAELens#368]
### Proposal 

Move to [Ruff](https://docs.astral.sh/ruff/) for linting and formatting

This is a follow-on from discussion in https://github.com/jbloomAus/SAELens/pull/226

### Motivation

Ruff combines Flake8, pylint, black, isort (and I think a few others) into a single package rewritten from scratch in Rust to be very fast. This means we can replace multiple dependencies with a single dependency, it's more flexible, and is also more performant. This seems to be where most of the Python community is heading.

This will let us enable pylint rules like suggested in #226

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/jbloomAus/SAELens/issues) in the repo (**required**)

**Comment by anthonyduong9** [comment]
I can work on this this weekend.

**Comment by anthonyduong9** [comment]
@chanind I'm working with the Ruff configuration in https://github.com/callummcdougall/sae_vis/pull/33, but with version `^0.7.4`, and `exclude = ["*.ipynb"]` for `[tool.ruff.lint]`. I'm thinking we'll just have to add `# noqa: ARG001` next to all the hook functions. So I don't have to fix a bunch of errors more than once, does this sound good to you?

**Comment by chanind** [comment]
That sounds reasonable to me! Also feel free to add any more linting rules you think make sense

**Comment by oli-clive-griffin** [comment]
How are you going on this @anthonyduong9? I'm keen to start contributing to SAELens and this seems like a nice place to start if you'd like to hand it off to someone? I've set up ruff on other projects before too. :)

**Comment by anthonyduong9** [comment]
> How are you going on this @anthonyduong9? I'm keen to start contributing to SAELens and this seems like a nice place to start if you'd like to hand it off to someone? I've set up ruff on other projects before too. :)

Oh, sorry I haven't commented in a while - I've pushed all my changes to a branch and am going to open a PR once https://github.com/jbloomAus/SAELens/pull/388 merges, since it wasn't clear if/how I could stack PRs to this repo. I'm sure there's another issue in the tracker that'd be good to start off with though.
