### ISSUE TITLE
[Bug Report] fold_activation_norm_scaling_factor should be performed before saving all checkpoints, not only the final checkpoint

### ISSUE THREAD

**Issue by chanind** [jbloomAus/SAELens#381]
If using `normalize_activations` = `expected_average_only_in`, we scale activations by a scaling factor being training the SAE. Without calling `fold_activation_norm_scaling_factor()`, the SAE will not work properly with unscaled activations. We do not save the scaling factor along with the SAE, so there's no way to use an SAE that's been saved without the activation scaling also being saved or folded in.

SAELens trainer calls  `fold_activation_norm_scaling_factor()` before saving the final checkpoint, but this is not called before intermediate checkpoints. This means the intermediate checkpoints are not usable SAEs. 

We should either call `fold_activation_norm_scaling_factor()` before saving a checkpoint, or include the norm scaling factor somehow when saving the checkpoint. A complication with the `fold_activation_norm_scaling_factor()` approach is that we need to do it only on the version of the SAE weights being saved, not on the in-progress SAE being trained.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/jbloomAus/SAELens/issues) in the repo (**required**)

**Comment by oli-clive-griffin** [comment]
> we scale activations by a scaling factor being training the SAE
Do you mean "before training the SAE"?

**Comment by oli-clive-griffin** [comment]
while getting familiar with the code, I think I may have come across a bug, hope I've just got the math wrong:

https://github.com/jbloomAus/SAELens/blob/d027158e2b4de4db25e15457f203f8aa0a9c193b/sae_lens/sae.py#L485:L495

**Comment by oli-clive-griffin** [comment]
PR is up :)
