### ISSUE TITLE
Move to safetensors to save autoencoders and activations

### ISSUE THREAD

**Issue by chanind** [jbloomAus/SAELens#42]
Currently saving and loading uses `torch.save()`, but this allows malicious code to be executed while loading. Huggingface developed a format called safetensors (https://huggingface.co/docs/safetensors/en/index) which cannot be used to load executable code, and is also much faster than torch.save/torch.load for loading tensors (supposedly [76x faster](https://huggingface.co/docs/safetensors/en/speed)). I think it also allows reading the size of the stored tensors without loading the entire file, which would be a big win when initializing `ActivationsStore`.

**Comment by jbloomAus** [comment]
Sounds great!

**Comment by jbloomAus** [comment]
I've done this for autoencoders but not for activations.
