### ISSUE TITLE
Use logging instead of print in codebase

### ISSUE THREAD

**Issue by chanind** [jbloomAus/SAELens#43]
Currently, logging info is output using `print()`, but this makes it hard to control the verbosity level of the output, and cannot distinguish between debugging / info statements and warnings / errors. For instance, in [sae_training/config.py](https://github.com/jbloomAus/mats_sae_training/blob/main/sae_training/config.py#L117-L155), creating a config object prints a lot of statements, but these are a mix of debugging / info / warnings, and would be better suited to using the Python [logging module](https://docs.python.org/3/library/logging.html).

**Comment by anthonyduong9** [comment]
I can work on this this week.

**Comment by anthonyduong9** [comment]
@chanind there are many tests and `.ipynb` files with `print()`. It's not clear to me if `print()` or `logging` is better there, and for tests, if we should have `print()` or `logging` at all. What do you think?

**Comment by chanind** [comment]
I feel like print is fine for jupyter notebooks, and agree, unit tests shouldn't have print statements ideally - prints in unit tests should be deleted. Maybe benchmark tests are OK to have print statements since we don't really run those except manually and rarely.

**Comment by anthonyduong9** [comment]
@chanind I noticed in the few places we do use the `logging` package, we don't request a logger, i.e. have

`logger = logging.getLogger(__name__)`

even though it's considered best practice. I just want to make sure I'm not missing something.

If we do want to request a logger, we can do it once for the whole library (I was thinking in the root directory's `__init__.py`), or in each module. What do you think?

**Comment by chanind** [comment]
Sorry for the slow reponse - missed this somehow! using a single logger instance makes sense to me!
