### ISSUE TITLE
Add tests for `training/cache_activations_runner.py`

### ISSUE THREAD

**Issue by chanind** [jbloomAus/SAELens#83]
This is currently a big hole in the test coverage for training code. Current coverage: https://app.codecov.io/gh/jbloomAus/SAELens/blob/main/sae_lens%2Ftraining%2Fcache_activations_runner.py

**Comment by jbloomAus** [comment]
Makes sense. I'd like to see us move from storing tensors with torch.save
to using safetensors (or better yet, np.memmap was raised with me as a
possible useful utility)
