### ISSUE TITLE
Add toy models architecture built on HookedRootModule

### ISSUE THREAD

**Issue by evanhanders** [jbloomAus/SAELens#85]
Per discussion in slack, SAELens has stale code for toy models. It would be great to bring that code back to life.

Toy models should be built on top of a class that itself is a subclass of HookedRootModule from transformer_lens, so that toy models can be run_with_cache and code for toy models and language models actually looks pretty similar.

For starters, the Anthropic ReLU output model is the only toy model we need working, but keeping generality for other types of models to be included in future PRs would be great!

Note: I'm going to be working on this this week (week of Apr 15), and wanted to make sure that it was visible that this is being thought about and worked on.

**Comment by evanhanders** [comment]
I've been working on this over at https://github.com/evanhanders/SAELens/tree/toy_models and wanted to leave some updates/thoughts in no particular order of importance:

1. [Toy models are now built on top of HookedRootModules](https://github.com/evanhanders/SAELens/blob/toy_models/sae_lens/training/toy_models.py). Right now we have the framework implemented for training multiple instances of a toy model at a time, but we don't have that framework available for SAEs. I think that's eventually important, but right now I'm making the choice to just force the user to only train an SAE on a single-instance toy model. Thoughts on how this should be handled?
2. [I made LanguageModelSAERunnerConfig inherit from CacheActivationsRunnerConfig and got rid of duplicate code between the two](https://github.com/evanhanders/SAELens/blob/toy_models/sae_lens/training/config.py). I think this can still be cleaner. Toy models don't really have model names or dataset paths, so even the CacheActivationsRunnerConfig has some attributes that aren't useful to toy models but are essential to LMs. Otherwise all of the SAE training configuration in the LanguageModelSAERunner actually seems to not be specific to language models. Thoughts on how to organize this?
3. [ActivationsStores are now abstract classes and there's a specific LM and Toy inherited class to deal with synthetic vs real datasets](https://github.com/evanhanders/SAELens/blob/toy_models/sae_lens/training/activations_store.py).
4. Should I be renaming things? I['ve gone ahead and added a toy model sae runner to the lm_runner.py file and I've gotten rid of deprecated toy model runners since stuff kinda works off the same architecture under the hood and those shouldn't be separated](https://github.com/evanhanders/SAELens/blob/toy_models/sae_lens/training/lm_runner.py). Should I rename this model_runner? (this would require a version bump with an eventual PR merge I assume, and maybe that's too hairy for now).
5. [Evals were pretty easy to generalize](https://github.com/evanhanders/SAELens/blob/toy_models/sae_lens/training/evals.py). I removed the "ce" from the various dictionary names to say that it's just generally model loss and otherwise not much changed there. Are there specific evals I should add for toy models since we actually know the real features? (like, fraction of features that are monosemantically captured or something like that?)
6. I'm still thinking about what the structure of a good notebook is that guides people through this.
7. Toy models SAEs on with neuron resampling than ghost grads. Should I reimplement resampling?
8. I added a classifier toy model trained on CE loss cause language models are trained on CE loss and we should have toy models that have the same loss.
9. It would be really nice to have an "encode" and "decode" function in the SAE. This would also make the forward pass easier to read. Encode() would do everything from x-> feature_acts, and decode() would do feature_acts -> sae_out. The reason I'd like to have these is because I'd like to see what the activations (encoding) look like of e.g., an identity matrix of toy data looks. I can reproduce the logic outside of forward(), but making an encode() function that forward() uses and that I can reuse would be great.

This is kinda a lot. @jbloomAus @chanind -- thoughts on any of this and how to proceed?

**Comment by jbloomAus** [comment]
Ok, sorry for the late response. I wrote this then realised it was super old. Ahh will hit enter anyway. 

A few comments. @evanhanders 

> [Toy models are now built on top of HookedRootModules](https://github.com/evanhanders/SAELens/blob/toy_models/sae_lens/training/toy_models.py). Right now we have the framework implemented for training multiple instances of a toy model at a time, but we don't have that framework available for SAEs. I think that's eventually important, but right now I'm making the choice to just force the user to only train an SAE on a single-instance toy model. Thoughts on how this should be handled?

Sounds good. I think the answer about training multiple SAEs on different stores in the same runner for the time being is "we don't want to make massive changes to the runner for this reason, but we do want to refactor it to be easier to handle this in the near future". I understand your motivation though. Let's come back to this later. Possibly make an issue for it (and put my comment from here on the issue). 

> [I made LanguageModelSAERunnerConfig inherit from CacheActivationsRunnerConfig and got rid of duplicate code between the two](https://github.com/evanhanders/SAELens/blob/toy_models/sae_lens/training/config.py).

We had it with subclassing and undid that for various reasons. Don't worry about undoing it but just wanted to let you know. I'll be making some PRs soon and will make a call about whether we should keep the sub-class structure. Probably what we'll do is have an activation store config. which is shared by two seperate classes. 

> [ActivationsStores are now abstract classes and there's a specific LM and Toy inherited class to deal with synthetic vs real datasets](https://github.com/evanhanders/SAELens/blob/toy_models/sae_lens/training/activations_store.py).

This is reasonable. Thanks for that. 

> [Evals were pretty easy to generalize](https://github.com/evanhanders/SAELens/blob/toy_models/sae_lens/training/evals.py). I removed the "ce" from the various dictionary names to say that it's just generally model loss and otherwise not much changed there. Are there specific evals I should add for toy models since we actually know the real features? (like, fraction of features that are monosemantically captured or something like that?)

We definitely want specific evals associated with knowing the true features!  I'd make an issue for this with everything you want to add and make it clear they need to ignored for LMs. Possibly adding a config arg.  I don't love that you removed the CE from the losses as I think this makes it confusing. Saying model_loss rather than CE_loss would be fine though. 

> Should I be renaming things? I['ve gone ahead and added a toy model sae runner to the lm_runner.py file and I've gotten rid of deprecated toy model runners since stuff kinda works off the same architecture under the hood and those shouldn't be separated](https://github.com/evanhanders/SAELens/blob/toy_models/sae_lens/training/lm_runner.py). Should I rename this model_runner? (this would require a version bump with an eventual PR merge I assume, and maybe that's too hairy for now).

If you change what something is, the name should be changed to reflect this.  I'll handle this now. 

> Toy models SAEs on with neuron resampling than ghost grads. Should I reimplement resampling?

Not a priority for me. I think it's gone out of fashion. If someone does reimplement it, factoring it nicely seems important. 

> It would be really nice to have an "encode" and "decode" function in the SAE. This would also make the forward pass easier to read. Encode() would do everything from x-> feature_acts, and decode() would do feature_acts -> sae_out. The reason I'd like to have these is because I'd like to see what the activations (encoding) look like of e.g., an identity matrix of toy data looks. I can reproduce the logic outside of forward(), but making an encode() function that forward() uses and that I can reuse would be great.

We did this? Oh shit. This comment is like 2 weeks old.
